import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Implemento } from './implemento';
import { Observable } from 'rxjs';
import {ImplementoDetail} from './implemento-detail';
import {environment} from '../../environments/environment';

const API_URL = environment.apiURL;
const implementos = '/implementos';

/**
* The service provider for everything related to editorials
*/
@Injectable()
export class ImplementoService {
    
    /**
    * Constructor of the service
    * @param http The HttpClient - This is necessary in order to perform requests
    */
    constructor( private http: HttpClient) { }
  
    getImplementos() : Observable<Implemento[]> {
        return this.http.get<Implemento[]>(API_URL + implementos);
    }
    
    getImplementoDetail(implementoId): Observable<ImplementoDetail> {
        return this.http.get<ImplementoDetail>(API_URL + implementos + '/' + implementoId);
    }
    
    /**
    * Creates an implemento
    * @param implemento The new implemento
    * @returns The new implemento with the new id
    */
    createImplemento(implemento): Observable<Implemento> {
        return this.http.post<Implemento>(API_URL + implementos, implemento);
    }
    
    /**
    * The function which handles the errors generated by the requests
    * @param error The error which the API REST returned
    */
    /**private handleError(error: any) {
        return throwError(error.error.errorMessage);
    }**/
}
